# Please note that emoji usages follows this guide: https://gitmoji.dev/
---
name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: '✨ New Features/ Enhancements'
    when:
      labels:
        - 'feature'
        - 'enhancement'
        - 'feat'
        - 'improvement'
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
  - title: '📝 Documentation'
    when:
      labels:
        - 'documentation'
        - 'doc'
        - 'docs'
  - title: '🧩 Dependencies'
    when:
      labels:
        - 'dependencies'
        - 'dependency'
  - title: '💚 Chores'
    when:
      labels:
        - 'chores'
        - 'chore'
  - type: 'pre-exclude'
    when:
      labels:
        - 'skip-changelog'
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      labels:
        - 'major'
        - 'breaking'
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      labels:
        - 'documentation'
        - 'doc'
        - 'docs'
        - 'patch'
        - 'fix'
        - 'bugfix'
        - 'bug'
        - 'chore'
        - 'chores'
...
