= Asciidoctor Docker Container
:source-highlighter: coderay

== The environment

This Docker container provides:

* Asciidoctor 1.5.2
* Aciidoctor Diagram with Graphviz integration so you can use plantuml and graphiz diagrams
* Asciidoctor PDF (alpha)
* Asciidoctor EPUB3 (alpha)
* Source highlighting using CodeRay or Pygments
* Asciidoctor backends

== How to use it

Just run:

[source,bash]
----
docker run -it -v <your directory>:/documents/ gscheibel/asciidoctor
----

It will be directly mapped with [path]_/documents_ of the container.

Once started, you just have to create AsciiDoc files (in the directory mentioned above) and run Asciidoctor commands like:

* To run Asciidoctor on a basic AsciiDoc file:
+
[source,bash]
----
asciidoctor sample.adoc
asciidoctor-pdf sample.adoc
asciidoctor-epub3 sample.adoc
----

* To run AsciiDoc on an AsciiDoc file that contains diagrams:
+
[source,bash]
----
asciidoctor -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-pdf -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-epub3 -r asciidoctor-diagram sample-with-diagram.adoc
----

* To use Asciidoctor-backends use +-T+ with either `/asciidoctor-backends` or `$BACKENDS` followed by the backend you want to use. For example:
[source,bash]
----
asciidoctor -T /asciidoctor-backends/slim/dzslides myFile.adoc
#or
asciidoctor -T $BACKENDS/slim/dzslides myFile.adoc
----
