= Asciidoctor Docker Container
:source-highlighter: coderay

== The environment

This Docker container provides:

* Asciidoctor 1.5.4
* Aciidoctor Diagram with Graphviz integration so you can use plantuml and graphiz diagrams
* Asciidoctor PDF (alpha)
* Asciidoctor EPUB3 (alpha)
* Source highlighting using CodeRay or Pygments
* Asciidoctor backends
* Asciidoctor-fopub
* Asciidoctor-confluence
* Lazybones (for Asciidoctor-revealjs)

== How to use it

Just run:

[source,bash]
----
docker run -it -v <your directory>:/documents/ asciidoctor/docker-asciidoctor
----

It will be directly mapped with [path]_/documents_ of the container.

Once started, you just have to create AsciiDoc files (in the directory mentioned above) and run Asciidoctor commands like:

* To run Asciidoctor on a basic AsciiDoc file:
+
[source,bash]
----
asciidoctor sample.adoc
asciidoctor-pdf sample.adoc
asciidoctor-epub3 sample.adoc
----

* To run AsciiDoc on an AsciiDoc file that contains diagrams:
+
[source,bash]
----
asciidoctor -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-pdf -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-epub3 -r asciidoctor-diagram sample-with-diagram.adoc
----

* To use Asciidoctor-backends use +-T+ with either `/asciidoctor-backends` or `$BACKENDS` followed by the backend you want to use. For example:
[source,bash]
----
asciidoctor -T /asciidoctor-backends/slim/dzslides myFile.adoc
#or
asciidoctor -T $BACKENDS/slim/dzslides myFile.adoc
----

* To use fopub, you first need to generate the docbook file then use fopub:
+
[source, bash]
----
asciidoctor -b docbook sample.adoc
fopub sample.xml
----

* To use asciidoctor-confluence
+
[source, bash]
----
asciidoctor-confluence --host HOSTNAME --spaceKey SPACEKEY --title TITLE --username USER --password PASSWORD sample.adoc
----

== How to build it / Contribute

=== Requirements

If you want to build and test this images, you will need :

* bash
* make
* https://github.com/sstephenson/bats[Bats]
* Of course, a Docker client connected a Docker Engine

=== Quick start

Juste call make from the root of the repository :
[source, bash]
----
$ make
----

It will build the image and run tests against it.

=== In-depth

Make is just used to create a "workflow".
Thus, the underlying building and testing frameworks can be changed easily
without breaking all contributors habits.

There are 3 make targets :

* build : which goal is to create locally the Docker image
* test : launch the test suite against the local image
* all (default target) : Call the "build" AND "test" targets 
