= Asciidoctor Docker Container
:source-highlighter: coderay

== The environment

This Docker container provides:

* Asciidoctor 2.0.10
* Asciidoctor Diagram 1.5.18 with Graphviz integration (supports plantuml and graphiz diagrams)
* Asciidoctor PDF 1.5.0.beta.5
* Asciidoctor EPUB3 (alpha)
* Asciidoctor Mathematical
* AsciiMath
* Source highlighting using Rouge or CodeRay (Pygments not supported in the default Docker image as only Python 3 is available)
* Asciidoctor Confluence

== How to use it

Just run:

[source,bash]
----
docker run -it -v <your directory>:/documents/ asciidoctor/docker-asciidoctor
----

It will be directly mapped with [path]_/documents_ of the container.

Once started, you can use Asciidoctor commands to convert AsciiDoc files you created in the directory mentioned above. You can find several examples below.

* To run Asciidoctor on a basic AsciiDoc file:
+
[source,bash]
----
asciidoctor sample.adoc
asciidoctor-pdf sample.adoc
asciidoctor-epub3 sample.adoc
----

* To run AsciiDoc on an AsciiDoc file that contains diagrams:
+
[source,bash]
----
asciidoctor -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-pdf -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-epub3 -r asciidoctor-diagram sample-with-diagram.adoc
----

* To use Asciidoctor together with https://github.com/guard/guard[Guard]
Guard watches source files for changes and triggers asciidoctor automatically on every file change.
This setup with Guard is inspired from the asciidoctor
https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/#using-a-system-monitor[documentation].
+
The docker container should be started with an environment variable setting
[source, bash]
----
docker run \
       ... \
       -e ASCIIDOCTOR_COMMAND="asciidoctor index.adoc -r asciidoctor-diagram --out-file index.html 2>&1" \
       -e GUARD_WATCH="/.*\\.adoc$/" \
       ... \
       asciidoctor/docker-asciidoctor \
       guard start -G /Guardfile
----

* To use Asciidoctor Confluence:
+
[source, bash]
----
asciidoctor-confluence --host HOSTNAME --spaceKey SPACEKEY --title TITLE --username USER --password PASSWORD sample.adoc
----

* To use Asciidoctor reveal.js with local downloaded reveal.js:

[source,bash]
----
asciidoctor-revealjs sample-slides.adoc
asciidoctor-revealjs -r asciidoctor-diagram sample-slides.adoc
----

* To use Asciidoctor reveal.js with online reveal.js:

[source,bash]
----
asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0 sample-slides.adoc
asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0 -r asciidoctor-diagram sample-slides.adoc
----


* Batch mode. You can use it in a "batch" mode
+
[source, bash]
----
docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf index.adoc
----

== How to contribute / do it yourself ?

=== Requirements

You need the following tools:

* A bash compliant command line
* link:http://man7.org/linux/man-pages/man1/make.1.html[GNU make]
* link:https://github.com/sstephenson/bats[bats] installed and in your bash PATH
* Docker installed and in your path

=== How to build and test ?

* "bats" is used as a test suite runner. Since the ability to build is one way of testing, it is included.

* You just have to run the bats test suite, from the repository root:
+
[source,bash]
----
make test
----

==== Include test in your build pipeline or test manually

You can use bats directly to test the image, optional you can use a custome image name:

[source,bash]
----
# If you want to use a custom name for the image, OPTIONAL
export DOCKER_IMAGE_NAME_TO_TEST=your-image-name
bats tests/*.bats
----
